name: flighttime_games
description: Offline mini-games for airplane entertainment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  webview_flutter: ^4.4.2
  share_lib:
    path: ../../flutter_share_lib

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon/app-icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash.png
  ios: true

